# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mcsky's blog
iconURL: /img/pfp-2.png
email: vladseba@mcsky.ro
description: >- # this means to ignore newlines until "baseurl:"
  Mcblog
baseurl: "/" # the subpath of your site, e.g. /blog
domain: blog.mcsky.ro
url: "https://blog.mcsky.ro" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Mcsky231
github_username:  Mcsky23

# Build settings
markdown: kramdown
theme: jekyll-theme-leaf
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "img"
    values:
      image: true
      sitemap: false

hyvor_talk_website_id: 10812
google_analytics: G-JTY61S9N3E

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-JTY61S9N3E          # Required - replace with your tracking id
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
